// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/engine_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_Bid Type = 0
	Type_Ask Type = 1
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "Bid",
		1: "Ask",
	}
	Type_value = map[string]int32{
		"Bid": 0,
		"Ask": 1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_engine_service_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_proto_engine_service_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_engine_service_proto_rawDescGZIP(), []int{0}
}

type Class int32

const (
	Class_Market Class = 0
	Class_Limit  Class = 1
	Class_Stop   Class = 2
)

// Enum value maps for Class.
var (
	Class_name = map[int32]string{
		0: "Market",
		1: "Limit",
		2: "Stop",
	}
	Class_value = map[string]int32{
		"Market": 0,
		"Limit":  1,
		"Stop":   2,
	}
)

func (x Class) Enum() *Class {
	p := new(Class)
	*p = x
	return p
}

func (x Class) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Class) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_engine_service_proto_enumTypes[1].Descriptor()
}

func (Class) Type() protoreflect.EnumType {
	return &file_proto_engine_service_proto_enumTypes[1]
}

func (x Class) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Class.Descriptor instead.
func (Class) EnumDescriptor() ([]byte, []int) {
	return file_proto_engine_service_proto_rawDescGZIP(), []int{1}
}

type TimeInForce int32

const (
	TimeInForce_FOK TimeInForce = 0
	TimeInForce_IOC TimeInForce = 1
	TimeInForce_DAY TimeInForce = 2
	TimeInForce_GTC TimeInForce = 3
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "FOK",
		1: "IOC",
		2: "DAY",
		3: "GTC",
	}
	TimeInForce_value = map[string]int32{
		"FOK": 0,
		"IOC": 1,
		"DAY": 2,
		"GTC": 3,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_engine_service_proto_enumTypes[2].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_proto_engine_service_proto_enumTypes[2]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_proto_engine_service_proto_rawDescGZIP(), []int{2}
}

type Status int32

const (
	Status_New             Status = 0
	Status_Pending         Status = 1
	Status_PartiallyFilled Status = 2
	Status_Filled          Status = 3
	Status_Canceled        Status = 4
	Status_Rejected        Status = 5
	Status_Expired         Status = 6
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "New",
		1: "Pending",
		2: "PartiallyFilled",
		3: "Filled",
		4: "Canceled",
		5: "Rejected",
		6: "Expired",
	}
	Status_value = map[string]int32{
		"New":             0,
		"Pending":         1,
		"PartiallyFilled": 2,
		"Filled":          3,
		"Canceled":        4,
		"Rejected":        5,
		"Expired":         6,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_engine_service_proto_enumTypes[3].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_engine_service_proto_enumTypes[3]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_engine_service_proto_rawDescGZIP(), []int{3}
}

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_proto_engine_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_proto_engine_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_service_proto_rawDescGZIP(), []int{1}
}

func (x *CancelRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type Order struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	OwnerId        string                 `protobuf:"bytes,2,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
	Type           Type                   `protobuf:"varint,3,opt,name=Type,proto3,enum=proto.Type" json:"Type,omitempty"`
	TimeInForce    TimeInForce            `protobuf:"varint,4,opt,name=TimeInForce,proto3,enum=proto.TimeInForce" json:"TimeInForce,omitempty"`
	Class          Class                  `protobuf:"varint,5,opt,name=Class,proto3,enum=proto.Class" json:"Class,omitempty"`
	Status         Status                 `protobuf:"varint,6,opt,name=Status,proto3,enum=proto.Status" json:"Status,omitempty"`
	Quantity       int64                  `protobuf:"varint,7,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	FilledQuantity int64                  `protobuf:"varint,8,opt,name=FilledQuantity,proto3" json:"FilledQuantity,omitempty"`
	Price          int64                  `protobuf:"varint,9,opt,name=Price,proto3" json:"Price,omitempty"`
	Reserve        int64                  `protobuf:"varint,10,opt,name=Reserve,proto3" json:"Reserve,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Stop           bool                   `protobuf:"varint,12,opt,name=Stop,proto3" json:"Stop,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_engine_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_engine_service_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Order) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Bid
}

func (x *Order) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_FOK
}

func (x *Order) GetClass() Class {
	if x != nil {
		return x.Class
	}
	return Class_Market
}

func (x *Order) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_New
}

func (x *Order) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order) GetFilledQuantity() int64 {
	if x != nil {
		return x.FilledQuantity
	}
	return 0
}

func (x *Order) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetReserve() int64 {
	if x != nil {
		return x.Reserve
	}
	return 0
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetStop() bool {
	if x != nil {
		return x.Stop
	}
	return false
}

var File_proto_engine_service_proto protoreflect.FileDescriptor

const file_proto_engine_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/engine_service.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"0\n" +
	"\n" +
	"AddRequest\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.proto.OrderR\x05order\"*\n" +
	"\rCancelRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x95\x03\n" +
	"\x05Order\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x18\n" +
	"\aOwnerId\x18\x02 \x01(\tR\aOwnerId\x12\x1f\n" +
	"\x04Type\x18\x03 \x01(\x0e2\v.proto.TypeR\x04Type\x124\n" +
	"\vTimeInForce\x18\x04 \x01(\x0e2\x12.proto.TimeInForceR\vTimeInForce\x12\"\n" +
	"\x05Class\x18\x05 \x01(\x0e2\f.proto.ClassR\x05Class\x12%\n" +
	"\x06Status\x18\x06 \x01(\x0e2\r.proto.StatusR\x06Status\x12\x1a\n" +
	"\bQuantity\x18\a \x01(\x03R\bQuantity\x12&\n" +
	"\x0eFilledQuantity\x18\b \x01(\x03R\x0eFilledQuantity\x12\x14\n" +
	"\x05Price\x18\t \x01(\x03R\x05Price\x12\x18\n" +
	"\aReserve\x18\n" +
	" \x01(\x03R\aReserve\x128\n" +
	"\tCreatedAt\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12\x12\n" +
	"\x04Stop\x18\f \x01(\bR\x04Stop*\x18\n" +
	"\x04Type\x12\a\n" +
	"\x03Bid\x10\x00\x12\a\n" +
	"\x03Ask\x10\x01*(\n" +
	"\x05Class\x12\n" +
	"\n" +
	"\x06Market\x10\x00\x12\t\n" +
	"\x05Limit\x10\x01\x12\b\n" +
	"\x04Stop\x10\x02*1\n" +
	"\vTimeInForce\x12\a\n" +
	"\x03FOK\x10\x00\x12\a\n" +
	"\x03IOC\x10\x01\x12\a\n" +
	"\x03DAY\x10\x02\x12\a\n" +
	"\x03GTC\x10\x03*h\n" +
	"\x06Status\x12\a\n" +
	"\x03New\x10\x00\x12\v\n" +
	"\aPending\x10\x01\x12\x13\n" +
	"\x0fPartiallyFilled\x10\x02\x12\n" +
	"\n" +
	"\x06Filled\x10\x03\x12\f\n" +
	"\bCanceled\x10\x04\x12\f\n" +
	"\bRejected\x10\x05\x12\v\n" +
	"\aExpired\x10\x062\x83\x01\n" +
	"\rEngineService\x125\n" +
	"\bAddOrder\x12\x11.proto.AddRequest\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\vCancelOrder\x12\x14.proto.CancelRequest\x1a\x16.google.protobuf.EmptyB3Z1github.com/KedroPedro/order-matching-engine/protob\x06proto3"

var (
	file_proto_engine_service_proto_rawDescOnce sync.Once
	file_proto_engine_service_proto_rawDescData []byte
)

func file_proto_engine_service_proto_rawDescGZIP() []byte {
	file_proto_engine_service_proto_rawDescOnce.Do(func() {
		file_proto_engine_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_engine_service_proto_rawDesc), len(file_proto_engine_service_proto_rawDesc)))
	})
	return file_proto_engine_service_proto_rawDescData
}

var file_proto_engine_service_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_engine_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_engine_service_proto_goTypes = []any{
	(Type)(0),                     // 0: proto.Type
	(Class)(0),                    // 1: proto.Class
	(TimeInForce)(0),              // 2: proto.TimeInForce
	(Status)(0),                   // 3: proto.Status
	(*AddRequest)(nil),            // 4: proto.AddRequest
	(*CancelRequest)(nil),         // 5: proto.CancelRequest
	(*Order)(nil),                 // 6: proto.Order
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_proto_engine_service_proto_depIdxs = []int32{
	6, // 0: proto.AddRequest.order:type_name -> proto.Order
	0, // 1: proto.Order.Type:type_name -> proto.Type
	2, // 2: proto.Order.TimeInForce:type_name -> proto.TimeInForce
	1, // 3: proto.Order.Class:type_name -> proto.Class
	3, // 4: proto.Order.Status:type_name -> proto.Status
	7, // 5: proto.Order.CreatedAt:type_name -> google.protobuf.Timestamp
	4, // 6: proto.EngineService.AddOrder:input_type -> proto.AddRequest
	5, // 7: proto.EngineService.CancelOrder:input_type -> proto.CancelRequest
	8, // 8: proto.EngineService.AddOrder:output_type -> google.protobuf.Empty
	8, // 9: proto.EngineService.CancelOrder:output_type -> google.protobuf.Empty
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_engine_service_proto_init() }
func file_proto_engine_service_proto_init() {
	if File_proto_engine_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_engine_service_proto_rawDesc), len(file_proto_engine_service_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_engine_service_proto_goTypes,
		DependencyIndexes: file_proto_engine_service_proto_depIdxs,
		EnumInfos:         file_proto_engine_service_proto_enumTypes,
		MessageInfos:      file_proto_engine_service_proto_msgTypes,
	}.Build()
	File_proto_engine_service_proto = out.File
	file_proto_engine_service_proto_goTypes = nil
	file_proto_engine_service_proto_depIdxs = nil
}
